// <auto-generated />
using System;
using ARS_OS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ARSOS.Migrations
{
    [DbContext(typeof(AdessoRideShareDbContext))]
    [Migration("20230107151039_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ARS_OS.Models.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.ToTable("City");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1738578d-4cea-4911-b109-32c582bb46c2"),
                            Name = "City-0"
                        },
                        new
                        {
                            Id = new Guid("ee1fe3ae-1b01-41c0-b7cf-22e51de587e8"),
                            Name = "City-1"
                        },
                        new
                        {
                            Id = new Guid("20975fe9-2072-4b58-b4c0-d9e9df3d7cc7"),
                            Name = "City-2"
                        },
                        new
                        {
                            Id = new Guid("459c229d-c6ab-492a-b028-0b19a7aaa97f"),
                            Name = "City-3"
                        },
                        new
                        {
                            Id = new Guid("83abb108-7ba8-4654-ada6-15269b7444f3"),
                            Name = "City-4"
                        },
                        new
                        {
                            Id = new Guid("e0039304-4268-4f2e-9e6c-56361949c82d"),
                            Name = "City-5"
                        },
                        new
                        {
                            Id = new Guid("b4ff9a29-d963-48a5-bd56-e74ec054874c"),
                            Name = "City-6"
                        },
                        new
                        {
                            Id = new Guid("07c66830-94aa-4ced-b87d-e8c8defab428"),
                            Name = "City-7"
                        },
                        new
                        {
                            Id = new Guid("66c5caa3-5306-45f4-9de9-13645082a691"),
                            Name = "City-8"
                        },
                        new
                        {
                            Id = new Guid("3c200fd9-dacb-4018-9ea6-29498587ee0f"),
                            Name = "City-9"
                        },
                        new
                        {
                            Id = new Guid("db247f3d-bff2-421b-a429-35af1ffb5c91"),
                            Name = "City-10"
                        },
                        new
                        {
                            Id = new Guid("757d4e31-cc59-4d76-8cd6-68ee936ee321"),
                            Name = "City-11"
                        },
                        new
                        {
                            Id = new Guid("da7302a5-d904-4f58-b8ea-8c4c4fa02834"),
                            Name = "City-12"
                        },
                        new
                        {
                            Id = new Guid("40d6522a-b35c-4e00-abd1-70069c437fd1"),
                            Name = "City-13"
                        },
                        new
                        {
                            Id = new Guid("93bdb02e-8a27-4c23-98d3-154c6d5043f8"),
                            Name = "City-14"
                        },
                        new
                        {
                            Id = new Guid("a4877475-38e3-4b32-a88b-eb8d03f984e2"),
                            Name = "City-15"
                        },
                        new
                        {
                            Id = new Guid("e16e5dc1-90a1-4fef-a3e1-40a2fd0a7b69"),
                            Name = "City-16"
                        },
                        new
                        {
                            Id = new Guid("a707d25d-ca5a-4b46-8c6d-ca846eb9ad5b"),
                            Name = "City-17"
                        },
                        new
                        {
                            Id = new Guid("73df021c-5e6c-4b40-832c-92f1c92b7e46"),
                            Name = "City-18"
                        },
                        new
                        {
                            Id = new Guid("fc64f966-f4b9-4d3a-9645-049252f34fe1"),
                            Name = "City-19"
                        },
                        new
                        {
                            Id = new Guid("a452bff5-05a3-4c31-8a75-d55d4aceeb9e"),
                            Name = "City-20"
                        },
                        new
                        {
                            Id = new Guid("7194057e-c4c4-42d8-a72a-04de2ecc73ff"),
                            Name = "City-21"
                        },
                        new
                        {
                            Id = new Guid("44ff6c3f-22b2-4f0e-b758-c36e902364de"),
                            Name = "City-22"
                        },
                        new
                        {
                            Id = new Guid("2a048a86-b34a-45d4-9ebc-bd6676c33a21"),
                            Name = "City-23"
                        },
                        new
                        {
                            Id = new Guid("e67a81f7-7b24-43fc-b91d-88fcda1cece2"),
                            Name = "City-24"
                        },
                        new
                        {
                            Id = new Guid("6d7a3d44-cb34-4a2b-9844-d89bf5e0abea"),
                            Name = "City-25"
                        },
                        new
                        {
                            Id = new Guid("da164fb2-74e3-40d0-a0c4-45933bf3e305"),
                            Name = "City-26"
                        },
                        new
                        {
                            Id = new Guid("6a6de670-3c89-4eb2-97b7-b8d2e5123d6d"),
                            Name = "City-27"
                        },
                        new
                        {
                            Id = new Guid("e153cf0b-74d9-4351-a75f-85c5ff29d128"),
                            Name = "City-28"
                        },
                        new
                        {
                            Id = new Guid("0cffa918-bc4b-4ec9-88e5-a181224c5e8a"),
                            Name = "City-29"
                        },
                        new
                        {
                            Id = new Guid("03dea48b-ab18-42a6-8dab-e003280508de"),
                            Name = "City-30"
                        },
                        new
                        {
                            Id = new Guid("0fb98c9a-742d-4b62-9092-161608da596d"),
                            Name = "City-31"
                        },
                        new
                        {
                            Id = new Guid("91ffc99a-8666-4eca-b52b-fdf249ba783c"),
                            Name = "City-32"
                        },
                        new
                        {
                            Id = new Guid("f8414a3f-7760-48cb-880f-1a67ada1d9e2"),
                            Name = "City-33"
                        },
                        new
                        {
                            Id = new Guid("053bafa5-146c-4ddc-8674-1f4480892284"),
                            Name = "City-34"
                        },
                        new
                        {
                            Id = new Guid("09e949b1-78b6-4c4d-af21-5845439f14eb"),
                            Name = "City-35"
                        },
                        new
                        {
                            Id = new Guid("6d8b2a70-addf-48b0-ab43-0e0204db547d"),
                            Name = "City-36"
                        },
                        new
                        {
                            Id = new Guid("6b16e28b-8194-4052-9991-80dc53de90fa"),
                            Name = "City-37"
                        },
                        new
                        {
                            Id = new Guid("5e7e564a-3731-43d5-b6ec-3cfc8a743fe2"),
                            Name = "City-38"
                        },
                        new
                        {
                            Id = new Guid("39c8a18a-2c7e-4919-b161-60f1cad13816"),
                            Name = "City-39"
                        },
                        new
                        {
                            Id = new Guid("13b79484-9907-4b78-80db-e8b2f69a96e9"),
                            Name = "City-40"
                        },
                        new
                        {
                            Id = new Guid("5eb9439a-6e7c-4298-a849-0aa1a0fc2a5b"),
                            Name = "City-41"
                        },
                        new
                        {
                            Id = new Guid("6f3e5bc1-9b10-4155-ae06-09a55bcf13f0"),
                            Name = "City-42"
                        },
                        new
                        {
                            Id = new Guid("e68496ec-c237-4d0c-8c6a-037f319774a2"),
                            Name = "City-43"
                        },
                        new
                        {
                            Id = new Guid("be8cb903-5338-4a35-be77-bc7e09cf8380"),
                            Name = "City-44"
                        },
                        new
                        {
                            Id = new Guid("0b577d44-82ea-42e7-aa75-e145554c0ce7"),
                            Name = "City-45"
                        },
                        new
                        {
                            Id = new Guid("5ac56bd8-09b6-4f78-bcbb-9bee7a118bb6"),
                            Name = "City-46"
                        },
                        new
                        {
                            Id = new Guid("bbefdf57-6daa-4a14-b5d8-932f622e4f44"),
                            Name = "City-47"
                        },
                        new
                        {
                            Id = new Guid("070f741d-fefd-43de-89e8-e83f95b285c3"),
                            Name = "City-48"
                        },
                        new
                        {
                            Id = new Guid("7c4ea8b0-aaf0-470f-83c2-a6d537d3b509"),
                            Name = "City-49"
                        },
                        new
                        {
                            Id = new Guid("708f0bb8-1569-4acb-b6b3-ee7dab8d9ecb"),
                            Name = "City-50"
                        },
                        new
                        {
                            Id = new Guid("02794c02-5e1e-4843-92ed-07a3189e82be"),
                            Name = "City-51"
                        },
                        new
                        {
                            Id = new Guid("de1db5a8-1e1c-4efa-8b66-cd2a5ee020eb"),
                            Name = "City-52"
                        },
                        new
                        {
                            Id = new Guid("17462054-98ee-4109-9891-411899d85d5c"),
                            Name = "City-53"
                        },
                        new
                        {
                            Id = new Guid("3a99578e-68d6-4980-8eec-5950091bbb62"),
                            Name = "City-54"
                        },
                        new
                        {
                            Id = new Guid("844e5240-888c-40d4-9cbd-abb5cdbb469c"),
                            Name = "City-55"
                        },
                        new
                        {
                            Id = new Guid("717d4112-2f24-44c4-9961-52447178a8b6"),
                            Name = "City-56"
                        },
                        new
                        {
                            Id = new Guid("6b222e79-cb80-4446-99cc-3a7eb818b9f3"),
                            Name = "City-57"
                        },
                        new
                        {
                            Id = new Guid("52e7e48b-29b7-4c99-98c6-4375c890ba17"),
                            Name = "City-58"
                        },
                        new
                        {
                            Id = new Guid("4159e8d7-8686-4907-9b05-387390d7f05a"),
                            Name = "City-59"
                        },
                        new
                        {
                            Id = new Guid("ba38dd1b-02bc-4dac-9104-f94cef480447"),
                            Name = "City-60"
                        },
                        new
                        {
                            Id = new Guid("367a7cdb-99bc-4165-8698-29b11133967c"),
                            Name = "City-61"
                        },
                        new
                        {
                            Id = new Guid("a4dd8975-a40d-4f14-99d7-5169412642ac"),
                            Name = "City-62"
                        },
                        new
                        {
                            Id = new Guid("a5e7b391-0ee3-4c7d-9475-d38d8eb45c1e"),
                            Name = "City-63"
                        },
                        new
                        {
                            Id = new Guid("9aafc901-f364-4672-b3e1-72048adefc43"),
                            Name = "City-64"
                        },
                        new
                        {
                            Id = new Guid("f5440356-16c5-44f3-b190-6d998735f95f"),
                            Name = "City-65"
                        },
                        new
                        {
                            Id = new Guid("6a4f0154-bede-4423-924a-885c91fcae35"),
                            Name = "City-66"
                        },
                        new
                        {
                            Id = new Guid("bb0b41b5-cc67-4f94-928f-e4832754ee4c"),
                            Name = "City-67"
                        },
                        new
                        {
                            Id = new Guid("d508f25b-ae1a-4c22-9e99-cc2bbb9b8301"),
                            Name = "City-68"
                        },
                        new
                        {
                            Id = new Guid("d8847565-48c5-4c53-8150-0d131c7ee108"),
                            Name = "City-69"
                        },
                        new
                        {
                            Id = new Guid("7f71ff03-63f0-47c2-952c-1e0945e4b344"),
                            Name = "City-70"
                        },
                        new
                        {
                            Id = new Guid("febd3d5e-294a-4afb-ab64-79839df930c4"),
                            Name = "City-71"
                        },
                        new
                        {
                            Id = new Guid("74f40b5e-2c88-43b9-9ab5-91266be7e7ad"),
                            Name = "City-72"
                        },
                        new
                        {
                            Id = new Guid("eb7f701b-00c5-43e0-bf18-29ea4dc1263f"),
                            Name = "City-73"
                        },
                        new
                        {
                            Id = new Guid("c542dce4-94e1-4cd7-92f8-ab44536a1a97"),
                            Name = "City-74"
                        },
                        new
                        {
                            Id = new Guid("e9848bca-6baf-45e9-99b7-67aede246418"),
                            Name = "City-75"
                        },
                        new
                        {
                            Id = new Guid("4b46b18c-a74a-41b3-ba2c-0c7b34d72bdf"),
                            Name = "City-76"
                        },
                        new
                        {
                            Id = new Guid("7e811493-86c4-4ed1-940b-f85e30878097"),
                            Name = "City-77"
                        },
                        new
                        {
                            Id = new Guid("c28e108a-1fac-442d-b6ac-6b799f694470"),
                            Name = "City-78"
                        },
                        new
                        {
                            Id = new Guid("fba5eff5-ce1f-4761-a0be-5d74bbd2f4f1"),
                            Name = "City-79"
                        },
                        new
                        {
                            Id = new Guid("6f2a4e41-0ca0-49c0-9529-dee121ee16be"),
                            Name = "City-80"
                        },
                        new
                        {
                            Id = new Guid("b94c3c49-0eff-4f22-9d21-c45894edc1ce"),
                            Name = "City-81"
                        },
                        new
                        {
                            Id = new Guid("85807125-a9b6-4fca-a15d-36f243eea1ff"),
                            Name = "City-82"
                        },
                        new
                        {
                            Id = new Guid("dc8b74ca-9fde-4265-a724-dae246107a2f"),
                            Name = "City-83"
                        },
                        new
                        {
                            Id = new Guid("e3482441-312d-4a07-bec7-456579a17f99"),
                            Name = "City-84"
                        },
                        new
                        {
                            Id = new Guid("b98dd4ea-054a-450d-97f9-916519ed7f37"),
                            Name = "City-85"
                        },
                        new
                        {
                            Id = new Guid("75b03669-7ff0-4ad3-ba63-abbe0b218d75"),
                            Name = "City-86"
                        },
                        new
                        {
                            Id = new Guid("32a40b7d-3a0d-4625-9fba-f1897d55e67b"),
                            Name = "City-87"
                        },
                        new
                        {
                            Id = new Guid("aa438830-1586-43fd-b15a-a2a9028f739c"),
                            Name = "City-88"
                        },
                        new
                        {
                            Id = new Guid("54622d1f-a26d-43fd-8d32-bedbd37d14fd"),
                            Name = "City-89"
                        },
                        new
                        {
                            Id = new Guid("e0bb51a5-ec8d-4338-b9b4-ad3e795d2e17"),
                            Name = "City-90"
                        },
                        new
                        {
                            Id = new Guid("eb41cf64-ba63-4aba-8429-749bbf64fd0d"),
                            Name = "City-91"
                        },
                        new
                        {
                            Id = new Guid("7d045d05-3bbc-4f7d-b1d7-79f8dcf05b09"),
                            Name = "City-92"
                        },
                        new
                        {
                            Id = new Guid("9bed34f6-a6a9-42b6-8b73-ccda94177f1f"),
                            Name = "City-93"
                        },
                        new
                        {
                            Id = new Guid("48607860-76da-41ec-aeb0-517b641f27e2"),
                            Name = "City-94"
                        },
                        new
                        {
                            Id = new Guid("35849715-8138-45b3-95f4-5b3767afb6bd"),
                            Name = "City-95"
                        },
                        new
                        {
                            Id = new Guid("56525faf-1d88-419e-948c-53e13759c3bf"),
                            Name = "City-96"
                        },
                        new
                        {
                            Id = new Guid("501c118a-2baa-49d4-98ef-10ec558e6963"),
                            Name = "City-97"
                        },
                        new
                        {
                            Id = new Guid("637df89b-4e72-477c-a5a7-63a7c2e20417"),
                            Name = "City-98"
                        },
                        new
                        {
                            Id = new Guid("c7e519ac-47b9-4e0a-bde9-fe3fa0ecfb52"),
                            Name = "City-99"
                        },
                        new
                        {
                            Id = new Guid("45c73bdf-3a0b-4036-8aba-d384485d5ea3"),
                            Name = "City-100"
                        },
                        new
                        {
                            Id = new Guid("1afe0cfe-8259-4f72-ba22-a2d06c5c52b7"),
                            Name = "City-101"
                        },
                        new
                        {
                            Id = new Guid("80a26550-f60b-4a28-a6c3-6b15aa2b4bc0"),
                            Name = "City-102"
                        },
                        new
                        {
                            Id = new Guid("e60aa296-b2e9-4dfb-9a7f-bbb73b75a02a"),
                            Name = "City-103"
                        },
                        new
                        {
                            Id = new Guid("423ed105-f574-4fc6-8afb-9b997110b5c8"),
                            Name = "City-104"
                        },
                        new
                        {
                            Id = new Guid("04dd46fa-a64c-478c-8bcb-d5830a373f0d"),
                            Name = "City-105"
                        },
                        new
                        {
                            Id = new Guid("4cfbb04f-eab5-41ce-9830-5458322dc73e"),
                            Name = "City-106"
                        },
                        new
                        {
                            Id = new Guid("a7aff055-32f4-4c89-b973-91846731a9ff"),
                            Name = "City-107"
                        },
                        new
                        {
                            Id = new Guid("cf51a87d-07ca-405a-997f-b2b81968a697"),
                            Name = "City-108"
                        },
                        new
                        {
                            Id = new Guid("a4166de6-3090-44b3-9090-344d87e8b396"),
                            Name = "City-109"
                        },
                        new
                        {
                            Id = new Guid("7cac8c97-9a50-4a56-afdb-ccae1cf78c65"),
                            Name = "City-110"
                        },
                        new
                        {
                            Id = new Guid("1b9920fc-634b-4cc6-baca-1a029be1fd2d"),
                            Name = "City-111"
                        },
                        new
                        {
                            Id = new Guid("be7ef447-2afa-40f2-81af-e67c8315a997"),
                            Name = "City-112"
                        },
                        new
                        {
                            Id = new Guid("e56770f1-1860-4749-8daa-09fbc2347cd1"),
                            Name = "City-113"
                        },
                        new
                        {
                            Id = new Guid("f9de72c5-b56a-4c73-a38f-5dc30cbff983"),
                            Name = "City-114"
                        },
                        new
                        {
                            Id = new Guid("50e602fc-502f-4d5b-9f93-8518db376fec"),
                            Name = "City-115"
                        },
                        new
                        {
                            Id = new Guid("f52135d7-0b66-4aeb-aeec-f3e4171e0660"),
                            Name = "City-116"
                        },
                        new
                        {
                            Id = new Guid("6016ac5e-ec8f-40f3-a938-7a2d0f744db9"),
                            Name = "City-117"
                        },
                        new
                        {
                            Id = new Guid("d69c8b51-8bdb-4fdd-ac1c-726ceb7585ee"),
                            Name = "City-118"
                        },
                        new
                        {
                            Id = new Guid("8717fb34-814e-42c4-87f3-b1d5569573fe"),
                            Name = "City-119"
                        },
                        new
                        {
                            Id = new Guid("6713c6a4-0f12-4834-a833-c8c8653fb3a9"),
                            Name = "City-120"
                        },
                        new
                        {
                            Id = new Guid("8105cc68-9c03-47fb-be7f-258bb9738279"),
                            Name = "City-121"
                        },
                        new
                        {
                            Id = new Guid("b1d8a0c0-a3db-48ea-958a-cdf1b97e95c8"),
                            Name = "City-122"
                        },
                        new
                        {
                            Id = new Guid("b78d4bee-440a-41dd-9c9b-2ff8ea809c4f"),
                            Name = "City-123"
                        },
                        new
                        {
                            Id = new Guid("244692c2-a84e-48ab-9e0d-3cb207d428dc"),
                            Name = "City-124"
                        },
                        new
                        {
                            Id = new Guid("2d247d0c-5bfe-4b30-86cc-40a999e37b17"),
                            Name = "City-125"
                        },
                        new
                        {
                            Id = new Guid("2e392b26-1642-4e06-91de-d4bc969b5f19"),
                            Name = "City-126"
                        },
                        new
                        {
                            Id = new Guid("96de619a-2c85-4cc7-a117-d305b5377087"),
                            Name = "City-127"
                        },
                        new
                        {
                            Id = new Guid("4f325369-3b96-428a-b778-a341367f0646"),
                            Name = "City-128"
                        },
                        new
                        {
                            Id = new Guid("f455d68a-3db0-41f9-9616-6cc9327314a1"),
                            Name = "City-129"
                        },
                        new
                        {
                            Id = new Guid("05c422fc-a55d-459f-8cbb-98db4c3606c6"),
                            Name = "City-130"
                        },
                        new
                        {
                            Id = new Guid("c5459159-d74c-4fd6-b597-7d9ac6156987"),
                            Name = "City-131"
                        },
                        new
                        {
                            Id = new Guid("d671a0ec-cf47-4b1a-aab8-22d6483889b6"),
                            Name = "City-132"
                        },
                        new
                        {
                            Id = new Guid("6a6ce1e8-240d-42c4-b621-433579079741"),
                            Name = "City-133"
                        },
                        new
                        {
                            Id = new Guid("82a4c8d8-c31a-4a80-a6a1-7cb45b425f0a"),
                            Name = "City-134"
                        },
                        new
                        {
                            Id = new Guid("29a0e08f-e598-46b6-9d71-2075ddc35eb8"),
                            Name = "City-135"
                        },
                        new
                        {
                            Id = new Guid("43b5c8c0-8e53-4e27-9263-ffa573c74e82"),
                            Name = "City-136"
                        },
                        new
                        {
                            Id = new Guid("0a7037b1-7762-48ca-9403-e75e8aba5134"),
                            Name = "City-137"
                        },
                        new
                        {
                            Id = new Guid("658ea75b-7c36-4288-99c8-d4829d67b7a4"),
                            Name = "City-138"
                        },
                        new
                        {
                            Id = new Guid("e85f1fc4-998b-4796-ba24-b57265702c5b"),
                            Name = "City-139"
                        },
                        new
                        {
                            Id = new Guid("3e241892-e8af-43ae-871c-d56c688c50dc"),
                            Name = "City-140"
                        },
                        new
                        {
                            Id = new Guid("8c15658f-6f3f-4345-8887-8b858bec8f1d"),
                            Name = "City-141"
                        },
                        new
                        {
                            Id = new Guid("308ca966-1f35-4302-a513-826f6104a21e"),
                            Name = "City-142"
                        },
                        new
                        {
                            Id = new Guid("72e5da4d-1a4b-430e-b3d6-6b2615f8d987"),
                            Name = "City-143"
                        },
                        new
                        {
                            Id = new Guid("5e490b9e-ff4b-4472-ab11-5ffd19c6b848"),
                            Name = "City-144"
                        },
                        new
                        {
                            Id = new Guid("cfc98f2a-e350-452e-b187-e5bad540b8e3"),
                            Name = "City-145"
                        },
                        new
                        {
                            Id = new Guid("8c740d1c-b14b-4613-bc88-a5ce843f63b8"),
                            Name = "City-146"
                        },
                        new
                        {
                            Id = new Guid("d94a92b1-06d4-4750-96be-cb8ee72e7377"),
                            Name = "City-147"
                        },
                        new
                        {
                            Id = new Guid("5b89146b-f5d5-46bf-b3bf-d182cc50672e"),
                            Name = "City-148"
                        },
                        new
                        {
                            Id = new Guid("2be7ae5d-7547-4b6b-ac3b-97914276099a"),
                            Name = "City-149"
                        },
                        new
                        {
                            Id = new Guid("020b48c5-dd05-428e-a160-c5a0109bdf12"),
                            Name = "City-150"
                        },
                        new
                        {
                            Id = new Guid("d6dda941-bde4-4190-b2d8-4dc385fd1305"),
                            Name = "City-151"
                        },
                        new
                        {
                            Id = new Guid("9d740c63-1ad4-43e7-a4b8-f9c485b0b8d3"),
                            Name = "City-152"
                        },
                        new
                        {
                            Id = new Guid("d1db1e06-ddb5-4530-9e99-71917a833554"),
                            Name = "City-153"
                        },
                        new
                        {
                            Id = new Guid("a7acbe8d-6581-4213-a14b-dd9f65213e7f"),
                            Name = "City-154"
                        },
                        new
                        {
                            Id = new Guid("7797bfb2-82eb-4cc1-bc56-2121ca2631aa"),
                            Name = "City-155"
                        },
                        new
                        {
                            Id = new Guid("b864728b-e2ff-448e-8cd4-7d8bff0975c5"),
                            Name = "City-156"
                        },
                        new
                        {
                            Id = new Guid("c499e2f4-3717-48e6-ad09-b2888e3440ea"),
                            Name = "City-157"
                        },
                        new
                        {
                            Id = new Guid("3d4a430d-6d0c-4331-a338-33ffbf389b6c"),
                            Name = "City-158"
                        },
                        new
                        {
                            Id = new Guid("c139c29c-c4e4-4449-bc42-373711d310dc"),
                            Name = "City-159"
                        },
                        new
                        {
                            Id = new Guid("e37ef719-6789-4a9b-88b7-555fe6721f5e"),
                            Name = "City-160"
                        },
                        new
                        {
                            Id = new Guid("bc639d49-420a-4748-a938-b41c896b012d"),
                            Name = "City-161"
                        },
                        new
                        {
                            Id = new Guid("c647cc26-b59a-48b6-8d66-ccabf9a48eab"),
                            Name = "City-162"
                        },
                        new
                        {
                            Id = new Guid("9afb3fea-a699-4c79-9bcf-d76754f42e95"),
                            Name = "City-163"
                        },
                        new
                        {
                            Id = new Guid("bcaf3f76-f723-490a-a667-44ec173afead"),
                            Name = "City-164"
                        },
                        new
                        {
                            Id = new Guid("f9f3d4bb-db78-4fe9-92d9-c161b06d3d64"),
                            Name = "City-165"
                        },
                        new
                        {
                            Id = new Guid("48d4ae85-a497-4c0c-bbe1-a1924390831a"),
                            Name = "City-166"
                        },
                        new
                        {
                            Id = new Guid("7a663c93-9138-47a4-b5ef-b6e51f0217fd"),
                            Name = "City-167"
                        },
                        new
                        {
                            Id = new Guid("6107ccd0-c767-4e35-9b05-7a59b0f16523"),
                            Name = "City-168"
                        },
                        new
                        {
                            Id = new Guid("a7851f9f-d173-4cb6-ab71-8420ccc47b43"),
                            Name = "City-169"
                        },
                        new
                        {
                            Id = new Guid("56c8beb6-4d7b-4c02-803f-6c3f0f100722"),
                            Name = "City-170"
                        },
                        new
                        {
                            Id = new Guid("695b98c5-4c98-4159-9acf-393ff90e2246"),
                            Name = "City-171"
                        },
                        new
                        {
                            Id = new Guid("93e6ff64-749a-4ae3-acc2-fe922c5d5499"),
                            Name = "City-172"
                        },
                        new
                        {
                            Id = new Guid("10d653c6-a297-45bb-9fc0-c4e7e30a108d"),
                            Name = "City-173"
                        },
                        new
                        {
                            Id = new Guid("e7be02da-c483-4755-8184-5512310e1e73"),
                            Name = "City-174"
                        },
                        new
                        {
                            Id = new Guid("0f338a07-9634-4b92-93ee-f29eed6d345e"),
                            Name = "City-175"
                        },
                        new
                        {
                            Id = new Guid("b3e2ade9-4bdd-4da8-91c2-3168ec2fa387"),
                            Name = "City-176"
                        },
                        new
                        {
                            Id = new Guid("c9163178-9e0b-4678-be6d-7b02a9c9ea56"),
                            Name = "City-177"
                        },
                        new
                        {
                            Id = new Guid("fbfa480a-9e55-4df6-aed7-eb2878288edf"),
                            Name = "City-178"
                        },
                        new
                        {
                            Id = new Guid("a5654624-586f-455d-b157-062f309e8145"),
                            Name = "City-179"
                        },
                        new
                        {
                            Id = new Guid("850fb5ac-b5a5-496b-8f45-e4d840f22c35"),
                            Name = "City-180"
                        },
                        new
                        {
                            Id = new Guid("0ddd57f7-6f47-4cea-914c-f78cc0c4fbc7"),
                            Name = "City-181"
                        },
                        new
                        {
                            Id = new Guid("c526adc9-b878-4b20-b53a-6d394b4987b9"),
                            Name = "City-182"
                        },
                        new
                        {
                            Id = new Guid("0daee2eb-b3e6-4219-94dd-c0381d3bffec"),
                            Name = "City-183"
                        },
                        new
                        {
                            Id = new Guid("e13d9785-f422-4457-ab19-20522dd08d98"),
                            Name = "City-184"
                        },
                        new
                        {
                            Id = new Guid("0253ba15-7f99-4087-b42b-bd1ac0e57503"),
                            Name = "City-185"
                        },
                        new
                        {
                            Id = new Guid("c9ec1526-769e-4bf3-b188-f3658081426b"),
                            Name = "City-186"
                        },
                        new
                        {
                            Id = new Guid("fe743d97-eba8-4226-9649-81ddd60e0216"),
                            Name = "City-187"
                        },
                        new
                        {
                            Id = new Guid("be2e5aa8-8a43-4a95-a303-37eb4405287d"),
                            Name = "City-188"
                        },
                        new
                        {
                            Id = new Guid("55061b5b-3e7a-4332-a4b4-2e3523512e11"),
                            Name = "City-189"
                        },
                        new
                        {
                            Id = new Guid("5721430e-d8a1-44aa-b25f-9eb5d76072a5"),
                            Name = "City-190"
                        },
                        new
                        {
                            Id = new Guid("77b0c612-79e4-4b96-8afc-9772bb0651bb"),
                            Name = "City-191"
                        },
                        new
                        {
                            Id = new Guid("c8d98f34-bb12-4fcf-9d7d-53e68c8b8c32"),
                            Name = "City-192"
                        },
                        new
                        {
                            Id = new Guid("17988d78-b6a8-4132-8dab-f5bbc60a7e5c"),
                            Name = "City-193"
                        },
                        new
                        {
                            Id = new Guid("d18c6a53-28a9-4f00-a625-a0eb24e21d55"),
                            Name = "City-194"
                        },
                        new
                        {
                            Id = new Guid("049bb20b-ee91-41d0-a0ae-2414fa5222c1"),
                            Name = "City-195"
                        },
                        new
                        {
                            Id = new Guid("82305772-f305-43ae-bb3b-f1202776a812"),
                            Name = "City-196"
                        },
                        new
                        {
                            Id = new Guid("ff7eb555-0a56-4798-9596-bb9b505ecd9d"),
                            Name = "City-197"
                        },
                        new
                        {
                            Id = new Guid("620d97fa-198f-45a2-b7e5-8f000cad9e36"),
                            Name = "City-198"
                        },
                        new
                        {
                            Id = new Guid("f5862e7f-344d-4304-93b5-4d8964daabbb"),
                            Name = "City-199"
                        });
                });

            modelBuilder.Entity("ARS_OS.Models.TripPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserIP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreateUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatePlanned")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("FromCityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<short>("NumberOfSeats")
                        .HasColumnType("smallint");

                    b.Property<bool>("Published")
                        .HasColumnType("bit");

                    b.Property<Guid>("ToCityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUserIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FromCityId");

                    b.HasIndex("ToCityId");

                    b.ToTable("TripPlan");
                });

            modelBuilder.Entity("ARS_OS.Models.TripPlanRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserIP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreateUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<short>("NumberOfSeats")
                        .HasColumnType("smallint");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUserIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.ToTable("TripPlanRequest");
                });

            modelBuilder.Entity("ARS_OS.Models.TripPlan", b =>
                {
                    b.HasOne("ARS_OS.Models.City", "FromCity")
                        .WithMany("TripPlansFrom")
                        .HasForeignKey("FromCityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ARS_OS.Models.City", "ToCity")
                        .WithMany("TripPlansTo")
                        .HasForeignKey("ToCityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FromCity");

                    b.Navigation("ToCity");
                });

            modelBuilder.Entity("ARS_OS.Models.TripPlanRequest", b =>
                {
                    b.HasOne("ARS_OS.Models.TripPlan", "TripPlan")
                        .WithMany("TripPlanRequests")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("TripPlan");
                });

            modelBuilder.Entity("ARS_OS.Models.City", b =>
                {
                    b.Navigation("TripPlansFrom");

                    b.Navigation("TripPlansTo");
                });

            modelBuilder.Entity("ARS_OS.Models.TripPlan", b =>
                {
                    b.Navigation("TripPlanRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
